export const NODE_TO_MOUNT = 'findAStoreModal';
export const DATA_COMP_ID = 'data-compid';
export const ACTION_NAMESPACE = 'FIND_A_STORE_MODAL';

export const FETCH_STORE_DETAILS = `${ACTION_NAMESPACE}_FETCH_STORE_DETAILS`;
export const FETCH_STORE_DETAILS_SUCCESS = `${ACTION_NAMESPACE}_FETCH_STORE_DETAILS_SUCCESS`;
export const FETCH_STORE_DETAILS_FAILURE = `${ACTION_NAMESPACE}_FETCH_STORE_DETAILS_FAILURE`;
export const POST_MY_STORE = `${ACTION_NAMESPACE}_POST_MY_STORE`;
export const SAVE_STORE_ID = `${ACTION_NAMESPACE}_SAVE_STORE_ID`;
export const SAVE_STORE_URL = `${ACTION_NAMESPACE}_SAVE_STORE_URL`;

export const COOKIE_STORE_ID = 'WC_StLocId';
export const COOKIE_SELECTED_STORE = 'WC_StLocId_Selected';

export const FIND_A_MODAL_STORE_STATUS = 'GLOBAL_HEADER_FIND_A_MODAL_STORE_STATUS';
export const PDP_PRODUCT_ITEM_ID = 'FAS_PDP_PRODUCT_ITEM_ID';

export const MY_STORE_DETAILS = 'MY_STORE_DETAILS';
