const ACTIONS_NAMESPACE = 'PRODUCT_DETAILS';
export const SAVE_PRODUCT_INFO = `${ACTIONS_NAMESPACE}_SAVE_PRODUCT_INFO`;
export const SAVE_PRODUCT_SUCCESS = `${ACTIONS_NAMESPACE}_SAVE_PRODUCT_SUCCESS`;
export const SAVE_PRODUCT_FAILURE = `${ACTIONS_NAMESPACE}_SAVE_PRODUCT_ERROR`;
export const SAVE_STORE_ID = 'FIND_A_STORE_MODAL_SAVE_STORE_ID';
