export const NODE_TO_MOUNT = 'productPrice';
export const DATA_COMP_ID = 'data-compid';
export const COLOR_CLEARANCE = '#ee0000';
export const COLOR_SECONDARY = '#7f7f7f';
export const KEY_TEXT_OUR_PRICE_IN_CART = 'TEXT_OUR_PRICE_IN_CART';
export const TEXT_OUR_PRICE_IN_CART = 'Our Price in Cart';
export const TEXT_COMPARE_AT = 'Compare at';
export const KEY_TEXT_CALL_PRIMARY_MESSAGE = 'TEXT_CALL_PRIMARY_MESSAGE';
export const KEY_TEXT_CALL_MESSAGE_NUMBER = 'KEY_TEXT_CALL_MESSAGE_NUMBER';
export const TEXT_CALL_PRIMARY_MESSAGE = 'For special pricing call';
export const TEXT_CALL_MESSAGE_NUMBER = '(888) 922-2336';
export const LIVE_CHAT_URL = '//academy.custhelp.com/app/chat/chat_launch/';
export const TEXT_LIVE_CHAT_MESSAGE = 'Live Chat For Price';
export const TEXT_CHAT_NOW = 'Chat Now';
export const TOOLTIP_TEXT = "The manufacturer asked us not to share the price until it's in your cart. It's just too good of a deal.";
export { KEY_WAS_NOW_PRICE, KEY_PRICE_IN_CART, KEY_CALL_FOR_PRICING, KEY_LIVE_CHAT } from './constants.message.keys';
